feat:add e2e coverage
freeCodeCamp/chapter pull request #1015
Opened 2022-04-17 23:31 UTC by Ismailtlem

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

2022-04-20 06:34 UTC, ojeytonwilliams commented
Hey @Ismailtlem let me know when you'd like me to review this.

2022-04-21 11:03 UTC, ojeytonwilliams requested changes
This is great, thanks @Ismailtlem!

One thing I was wondering: how does the full report look in CI?  It would be nice to see the details, so we know what needs to be improved:

2022-04-21 11:03 UTC, ojeytonwilliams commented on package.json
> +    "cypress:coverage:report": "npx nyc report --reporter=text-summary",
```suggestion
    "cypress:coverage:report": "npx nyc report",
```
Could we try this?

2022-04-21 17:26 UTC, Ismailtlem commented on package.json
> +    "cypress:coverage:report": "npx nyc report --reporter=text-summary",
Resolved

2022-04-21 17:30 UTC, ojeytonwilliams approved these changes

2022-04-21 17:31 UTC, merged

2022-04-21 17:34 UTC, ojeytonwilliams commented
This is great, I really like the expanded output.