fix: restrict user ban functionality to member with ChapterBanUser rule
freeCodeCamp/chapter pull request #1413
Opened 2022-08-17 07:09 UTC by shootermv

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes part of #1217

2022-08-17 10:53 UTC, ojeytonwilliams requested changes
Hey @shootermv, thanks for working on this. This should be a `ChapterPermission`, since a chapter admin should be able to ban people from their chapter, but no others.

Also, could you create a test that confirms this, that would be awesome.  The `rejects chapter admin from changing chapter user role` spec should be a good starting point, but with `'admin@of.chapter.two'` instead.  It will also need a `banChaperUser` Cypress command, obviously!

2022-09-12 10:21 UTC, shootermv commented
as far as i understood, test for `admin@of.chpater.two` not bale to ban user of chapter one need to be added, im i right?

2022-09-13 14:48 UTC, ojeytonwilliams requested changes
> as far as i understood, test for admin@of.chpater.two not able to ban user of chapter one need to be added, Am i right?

Yes, please!

2022-09-13 14:48 UTC, ojeytonwilliams commented on server/prisma/generator/factories/instanceRoles.factory.ts
> +      ChapterPermission.ChapterBanUser,
```suggestion
```
Members should not be able to ban anyone.

2022-09-13 14:48 UTC, ojeytonwilliams commented on server/prisma/generator/factories/instanceRoles.factory.ts
> +} from '../../../../common/permissions';
```suggestion
import { InstancePermission, Permission } from '../../../../common/permissions';
```
See below

2022-09-14 11:24 UTC, ojeytonwilliams requested changes
This is looking good, just the one nitpick:

2022-09-14 11:24 UTC, ojeytonwilliams commented on cypress/e2e/dashboard/chapters/users.cy.ts
> +    cy.logout();
```suggestion
```
`cy.login` changes the session, so there's no need to log out first.

2022-09-14 13:17 UTC, ojeytonwilliams approved these changes

2022-09-14 13:17 UTC, merged

2022-09-14 13:18 UTC, ojeytonwilliams commented
Thanks @shootermv :rocket: