feat: add decorator for CanBeBanned
freeCodeCamp/chapter pull request #1416
Opened 2022-08-17 20:32 UTC by hisnameispum

- [X] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [X] My pull request targets the `main` branch of Chapter.

Closes part of #1217(canBeBanned)

2022-08-18 07:55 UTC, ojeytonwilliams requested changes
Hi, @hisnameispum, thanks for working on this. Could you restore the chapter page? It seems to have been deleted by accident.

Also, to avoid regressions it would be great to have tests that confirm that the permissions work. Namely that users who should not be able to ban actually cannot.

https://github.com/freeCodeCamp/chapter/pull/1346 is a good example of this.

2022-08-18 07:55 UTC, ojeytonwilliams commented on server/prisma/generator/factories/instanceRoles.factory.ts
> +} from '../../../../common/permissions';
```suggestion
import { InstancePermission, Permission } from '../../../../common/permissions';
```
We members should not be able to ban users, so we do not need to pull out the chapter permissions here.

2022-08-18 07:55 UTC, ojeytonwilliams commented on server/prisma/generator/factories/instanceRoles.factory.ts
> +      ChapterPermission.ChapterBanUser,
```suggestion
```
As mentioned, this isn't something members should be able to do.

2022-09-09 10:23 UTC, ojeytonwilliams commented
Hi @hisnameispum if you've got a moment, could you take a look at the failing tests?

2022-09-16 06:00 UTC, Sboonny commented
@ojeytonwilliams, I am wondering how to find admin role in users because I can't find it.

![image](https://user-images.githubusercontent.com/88248797/190567052-54f5ce09-fa26-4d86-bd8e-ddb8be1b5deb.png)


I think the cypress test about finding admin role fails, because it doesn't exist in user dashboard

2022-09-16 11:09 UTC, ojeytonwilliams commented
> I am wondering how to find admin role in users because I can't find it.

There aren't instance admins (yet), since we figured they weren't MVP worthy.  The roles are instance owner, instance member, chapter admin and chapter member.

> after fixing status error, banned admin don't have permission to view the table at all

Yep, that's right. I'll update the tests.

2022-09-20 15:55 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-09-20 16:01 UTC, merged