fix: events loading inconsistency
freeCodeCamp/chapter pull request #1476
Opened 2022-08-30 19:03 UTC by gikf

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

---
- Fixes double load on opening `/events`, one coming from the normal query and one from `fetchMore` after `currentPage` is changed/set.
- Fetching more is now limited to not visited pages numbers. Otherwise (I assume) loaded previously page with events is loaded from cache (I assume). This might be a little overkill for now, both in doing so in first place and in using set to keep track of visited pages.

2022-09-05 12:56 UTC, ojeytonwilliams reviewed
Just to confirm: is the goal to prevent the client repeatedly requesting pages it has already fetched? e.g. if open events and click back and forth between pages 1 and 2 the browser should only make two GraphQL requests.

2022-09-05 16:47 UTC, gikf commented
> Just to confirm: is the goal to prevent the client repeatedly requesting pages it has already fetched? e.g. if open events and click back and forth between pages 1 and 2 the browser should only make two GraphQL requests.

As an additional effect - yes. The main goal was to stop loading, fetching and rendering twice when `/events` is opened for the first time.

2022-09-05 17:03 UTC, ojeytonwilliams commented
> As an additional effect - yes. The main goal was to stop loading, fetching and rendering twice when /events is opened for the first time.

I only see the one graphql request when I reload events.  Either way, I think this PR makes sense.

2022-09-05 18:00 UTC, gikf commented
Well, this is awkward. Scratch the fetching then please.

I've double checked how to reproduce the weird behavior that made us all gather here:
- Open home page.
- Navigate to _Events_ from _Menu_.
- Navigate to home page.
- Navigate to _Events_ from _Menu_. (Additionally this step often gets stuck with _Loading..._, in such case circling back home page -> Events would get it unstuck).
- List with events are displayed (that would be cache I believe now), but then _Loading..._ appears, and fresh list with events is fetched.

I've also found that's not fully resolved. I'll investigate further, but fresh eyes could spot something obvious.

2022-09-09 15:59 UTC, ojeytonwilliams requested changes
I like what you've done to reduce queries, but it got me thinking about why it was getting stuck on loading.  It seems like the incorrect offset was confusing it.

2022-09-09 15:59 UTC, ojeytonwilliams commented on client/src/modules/events/pages/eventsPage.tsx
> +  const [visitedPages, setVisitedPages] = useState(new Set([1]));
```suggestion
  const [visitedPages, setVisitedPages] = useState(new Set([1]));
  const offset = (currentPage - 1) * pageSize;
```

2022-09-09 15:59 UTC, ojeytonwilliams commented on client/src/modules/events/pages/eventsPage.tsx
>      variables: { offset: (currentPage - 1) * pageSize, limit: pageSize },
```suggestion
    variables: { offset, limit: pageSize },
```

2022-09-09 15:59 UTC, ojeytonwilliams commented on client/src/modules/events/pages/eventsPage.tsx
>          offset: data?.paginatedEventsWithTotal.events.length || 0,
```suggestion
        offset,
```

2022-09-09 19:30 UTC, ojeytonwilliams approved these changes
LGTM. Thanks!

2022-09-09 19:30 UTC, merged