fix: make dashboard consistent
freeCodeCamp/chapter pull request #1505
Opened 2022-09-07 14:01 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

This one makes dashboard consistent, but it has issues

2022-09-07 14:02 UTC, Sboonny commented on client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
> +                        keys={[' ', '_'] as const}
the underscore is showing, and I am sure it annoys screen readers as well.

2022-09-07 14:04 UTC, Sboonny reviewed
Spacing is still unfixable issue

2022-09-07 16:53 UTC, gikf commented
`DataTabale` has `showHeader` prop, which can be used to hide header

2022-09-13 15:40 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
> +                              <Text fontWeight={700}>Ops</Text>
```suggestion
                              <Text fontWeight={700}>Actions</Text>
```
To be consistent with the rest.

2022-09-13 16:08 UTC, ojeytonwilliams requested changes
Thanks @Sboonny, this is coming together.  The only thing that leapt out at me was the inconsistency between ops and action:

2022-09-13 16:08 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Events/pages/EventsPage.tsx
> +                          <Text>Ops</Text>
```suggestion
                          <Text>Actions</Text>
```

2022-09-13 16:26 UTC, Sboonny commented on client/src/modules/dashboard/Sponsors/pages/SponsorsPage.tsx
> +            <LinkButton href="/dashboard/sponsors/new" colorScheme={'blue'}>
I am used to if statements to block access, I have opened chapter.freecodecamp.org/dashboard/sponsers, and there were no buttons, so I am worried about nothing like usual.

2022-09-14 11:42 UTC, Sboonny commented on client/src/modules/dashboard/Chapters/Users/pages/ChapterUsersPage.tsx
> +                              <Text fontWeight={700}>Actions</Text>
```suggestion
                              <Text fontWeight={700}>Action</Text>

2022-09-14 11:44 UTC, ojeytonwilliams approved these changes

2022-09-14 12:12 UTC, merged