chore: create user profile
freeCodeCamp/chapter pull request #1567
Opened 2022-09-20 10:06 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

In this attempt, I won't try to add the ability to get more data, but will focus on deletion function.

2022-09-21 11:05 UTC, ojeytonwilliams requested changes

2022-09-21 11:05 UTC, ojeytonwilliams commented on client/src/modules/profiles/pages/userProfile.tsx
> +import { useAuth } from 'modules/auth/store';
```suggestion
import { useAuthStore } from 'modules/auth/store';
```
By using the store we can update the stored user after deleteMe resolves.

2022-09-21 11:05 UTC, ojeytonwilliams commented on client/src/modules/profiles/pages/userProfile.tsx
> +  const { user } = useAuth();
```suggestion
  const {
    data: { user },
    setData,
  } = useAuthStore();
```

2022-09-21 11:05 UTC, ojeytonwilliams commented on client/src/modules/profiles/pages/userProfile.tsx
> +    router.push('/');
```suggestion
    setData({});
    router.push('/');
```
Purge the stored user.

2022-09-21 17:36 UTC, ojeytonwilliams requested changes
I noticed, by chance, that banned users can't delete their accounts.  For the MVP I think we can allow that (even knowing that they can create new accounts to evade bans) and consider a proper solution later down the line. Could you make the `user_bans` cascade like the sessions?

2022-09-21 17:36 UTC, ojeytonwilliams commented on client/src/modules/auth/graphql/mutations.ts
> +    deleteMe(id: $userId) {
```suggestion
  mutation deleteMe {
    deleteMe {
```
By giving this an id parameter it implies that you can delete a user with that id.  That's not the case, so we should remove the parameter.

2022-09-21 17:36 UTC, ojeytonwilliams commented on server/src/controllers/Auth/resolver.ts
> +    @Arg('id', () => Int) id: number,
```suggestion
```
The queries should not be passing this id.

2022-09-21 17:36 UTC, ojeytonwilliams commented on server/src/controllers/Auth/resolver.ts
> +    if (id === ctx.user.id) return await prisma.users.delete({ where: { id } });
```suggestion
    return await prisma.users.delete({ where: { id: ctx.user.id } });
```

2022-09-21 18:09 UTC, gikf reviewed
Self note for future: remember to apply schema changes before wondering why updated relations do not cascade on deletion :eyes:

2022-09-22 16:17 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-09-22 16:22 UTC, merged