chore: replace event placeholder in venue page
freeCodeCamp/chapter pull request #1580
Opened 2022-09-22 12:04 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

- replace placeholders with chapter's event at `/dashboard/venues/{id}`

![image](https://user-images.githubusercontent.com/88248797/191741711-c65b054c-9090-4b6f-9da6-c779dc120413.png)

2022-09-23 18:46 UTC, gikf reviewed
I believe the displayed events are not necessarily hosted at the certain venue, but they are all organized by the _venue's_ chapter.

2022-09-23 20:45 UTC, Sboonny commented
True, I was worried it will be indistinguishable from other placeholders, but that didn't mean I should give false info. 

I will update it tomorrow morning 👍

2022-09-24 05:38 UTC, Sboonny commented on client/src/modules/dashboard/Venues/pages/VenuePage.tsx
> +        Hosted Events
```suggestion
Organized By The Venue's Chapter

2022-09-24 17:32 UTC, Sboonny commented on client/src/modules/dashboard/Venues/pages/VenuePage.tsx
> +        Organized By The Venue's Chapter
```suggestion
        Organized By The Venue&apos;s Chapter

2022-09-26 08:45 UTC, ojeytonwilliams requested changes

2022-09-26 08:45 UTC, ojeytonwilliams commented on server/src/controllers/Venue/resolver.ts
> +const VenuesData = {
```suggestion
const venueIncludes = {
```
For consistency with the rest of the codebase.

2022-09-26 08:45 UTC, ojeytonwilliams commented on server/src/controllers/Venue/resolver.ts
> +      },
```suggestion
      include: venueIncludes,
```

2022-09-26 08:45 UTC, ojeytonwilliams commented on server/src/controllers/Venue/resolver.ts
> +      include: VenuesData,
```suggestion
      include: venueIncludes,
```

2022-09-26 10:49 UTC, ojeytonwilliams approved these changes
Thanks, @Sboonny, this page is a lot less bare now. LGTM :+1:

2022-09-26 10:50 UTC, merged