Update me function and mutation
freeCodeCamp/chapter pull request #1589
Opened 2022-09-23 05:06 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #XXXXX

2022-09-25 18:19 UTC, gikf reviewed
The _original_ name in form doesn't change after saving, this makes reverting the change require reloading page:
- Change name from A to B.
- Press save button. Name B is saved.
- Change name in input to the name A.
- Save button is disabled.

I cannot make suggestions in these places in github, this can be fixed with following:
```
--- a/client/src/modules/profiles/component/ProfileForm.tsx
+++ b/client/src/modules/profiles/component/ProfileForm.tsx
@@ -1,5 +1,5 @@
 import { Button } from '@chakra-ui/react';
-import React from 'react';
+import React, { useEffect } from 'react';
 import { useForm } from 'react-hook-form';
 import { Input } from '../../../components/Form/Input';
 import { TextArea } from '../../../components/Form/TextArea';
@@ -40,11 +40,16 @@ export const ProfileForm: React.FC<ProfileFormProps> = (props) => {
   const {
     handleSubmit,
     register,
+    reset,
     formState: { isDirty },
   } = useForm<UpdateUserInputs>({
     defaultValues,
   });
 
+  useEffect(() => {
+    reset({ name: me });
+  }, [me]);
+
   return (
     <Form submitLabel={submitText} FormHandling={handleSubmit(onSubmit)}>
       {fields.map(({ key, label, placeholder, required, type }) =>
```

2022-09-25 18:22 UTC, gikf commented on client/src/modules/profiles/pages/userProfile.tsx
> +            submitText={'Save Chapter Changes'}
```suggestion
            loadingText={'Saving Profile Changes'}
            submitText={'Save Profile Changes'}
```

2022-09-26 08:53 UTC, ojeytonwilliams commented
> Another very specific issue is that client and server will accept blank spaces as name - .

I think an empty string is fine, but we should trim them so we don't have ' ' and '   ' be different names.

2022-09-26 09:40 UTC, ojeytonwilliams requested changes

2022-09-26 09:40 UTC, ojeytonwilliams commented on client/src/modules/profiles/pages/userProfile.tsx
> +      await router.push('/profile');
```suggestion
```
Is this necessary?

2022-09-26 09:40 UTC, ojeytonwilliams commented on client/src/modules/profiles/component/ProfileForm.tsx
> +  data: string;
```suggestion
  data: UpdateUserInputs;
```

2022-09-26 09:40 UTC, ojeytonwilliams commented on client/src/modules/profiles/component/ProfileForm.tsx
> +  const defaultValues: UpdateUserInputs = { name: me };
```suggestion
  const defaultValues: UpdateUserInputs = { name: data.name };
```

2022-09-26 09:40 UTC, ojeytonwilliams commented on client/src/modules/profiles/component/ProfileForm.tsx
> +  }, [me]);
```suggestion
    reset({ name: data.name });
  }, [data]);
```

2022-09-26 09:40 UTC, ojeytonwilliams commented on client/src/modules/profiles/pages/userProfile.tsx
> +            data={user.name.trim()}
```suggestion
            data={user}
```
This is more type-safe.  We have to provide `name`, not just any string.  We can trim the data in `submitUpdateMe`

2022-09-26 11:17 UTC, Sboonny reviewed
Reapply the suggestion

2022-09-26 11:17 UTC, Sboonny commented on client/src/modules/profiles/pages/userProfile.tsx
> +            data={user}
```suggestion
            data={data}
```

2022-09-26 14:37 UTC, ojeytonwilliams approved these changes
Thanks @Sboonny, this LGTM :+1:

2022-09-26 14:52 UTC, ojeytonwilliams approved these changes
I finally remembered we supposed to trim :cold_sweat: 

LGTM :+1:

2022-09-26 16:38 UTC, merged