chore: refactor create event form
freeCodeCamp/chapter pull request #1626
Opened 2022-09-28 17:20 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

this targets making the inputs more user friendly, I should replace foo bar from other forms but this for different PR

2022-10-04 12:34 UTC, Sboonny commented on cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
> +      if (!['tags', 'startAt', 'endAt', 'venueId'].includes(key)) {
```suggestion
      if (!['tags', 'start_at', 'ends_at', 'venue_id'].includes(key)) {

2022-10-06 08:49 UTC, ojeytonwilliams requested changes
Now the tags are gone, those tests will need updating. That should be all, though!

2022-10-06 08:49 UTC, ojeytonwilliams commented on cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
> +    // ToDo: textbox shouldn't use component's text to indicate if it can find the component.
```suggestion
```
We do need to improve the tests, but I'm not sure this is the way.

2022-10-06 08:49 UTC, ojeytonwilliams commented on cypress/e2e/dashboard/chapters/[chapterId]/chapterId-index.cy.ts
>      // cy.findByRole('textbox', { name: 'Url' }).type(testEvent.url);
```suggestion
```

2022-10-06 08:49 UTC, ojeytonwilliams commented on cypress/e2e/dashboard/events/events-index.cy.ts
> +    // ToDo: textbox shouldn't use component's text to indicate if it can find the component.
```suggestion
```

2022-10-14 16:16 UTC, ojeytonwilliams commented
Sorry for adding to your merge conflict burden :disappointed:

2022-10-14 16:27 UTC, Sboonny commented
Yeab, I have no problems with conflicts, no worries 👍

2022-10-19 12:15 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-10-19 12:16 UTC, merged