Refactor: remove events tags requirements from fields and resolvers
freeCodeCamp/chapter pull request #1632
Opened 2022-09-29 09:25 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

There is no reason to use eventTags every time we try to use Event, so this aims to separate them.

2022-10-05 16:50 UTC, Sboonny commented on server/prisma/generator/factories/events.factory.ts
> -    events.push(event.id);
I don't know why I have deleted factory, I guess I was on frenzy. anyway should they be brought back or when we try to use EventTags in the future we will use them?

2022-10-05 16:51 UTC, Sboonny commented on server/src/controllers/Events/resolver.ts
> +        data: {},
Shouldn't these be deleted as well? I amn't sure, but now they don't update anything

2022-10-06 07:36 UTC, ojeytonwilliams requested changes
Looking good, just one minor thing:

2022-10-06 07:36 UTC, ojeytonwilliams commented on server/src/graphql-types/Event.ts
> +
```suggestion
```
This doesn't get used, so we can remove it.

2022-10-06 08:39 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-10-06 08:40 UTC, merged