feat: fix flashing img while loading image
freeCodeCamp/chapter pull request #1769
Opened 2022-10-24 06:35 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #1755 

we are having an issue, `fallbackstratagy` in chakra doesn't do the intended function.

![image](https://user-images.githubusercontent.com/88248797/197462215-2f48fae9-decb-41ee-a1e6-c4e5f2a62633.png)

2022-10-24 12:58 UTC, ojeytonwilliams commented
Sorry, @Sboonny, I realise I wasn't terribly clear about this.  If there's no image at all, we don't need to fallback to an empty box. I think, in that case, it would be better to show nothing at all:

![image](https://user-images.githubusercontent.com/15801806/197530841-9f61aa58-e57d-4469-b3a6-27b0e9866865.png)

What do you reckon?

2022-10-24 13:18 UTC, Sboonny commented
Sure don't see why not 👍

2022-10-25 07:48 UTC, ojeytonwilliams requested changes

2022-10-25 07:48 UTC, ojeytonwilliams commented on client/src/modules/chapters/pages/chapterPage.tsx
> +        data.chapter.banner_url === null ? null : (
```suggestion
        {data.chapter.banner_url && (
```
The truthiness of `banner_url` is the only thing that matters here, so we can simplify a bit.

2022-10-25 07:48 UTC, ojeytonwilliams commented on client/src/modules/events/pages/eventPage.tsx
> +      ) : null}
```suggestion
      {data.event.image_url && (
        <Box height={'300px'}>
          <Image
            data-cy="event-image"
            boxSize="100%"
            maxH="300px"
            src={data.event.image_url}
            alt=""
            borderRadius="md"
            objectFit="cover"
            fallbackSrc="https://cdn.freecodecamp.org/chapter/brown-curtain-small.jpg"
            fallbackStrategy="onError"
          />
        </Box>
      )}
```
Same principle as above.

2022-10-25 08:31 UTC, ojeytonwilliams approved these changes
LGTM 👍

2022-10-25 08:46 UTC, merged