feat: don't send event invites if event starts in the past
freeCodeCamp/chapter pull request #1777
Opened 2022-10-24 19:45 UTC by gikf

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #1661

---

- Doesn't send event invite if event starts in the past. I think it's not needed to be very precise with that check.
- Changes default event start and end by one day.
- Wording for note and positioning could be better.

2022-10-31 18:47 UTC, gikf commented
I don't know what's the issue with test and I'm unable to reproduce it locally :thinking:

2022-11-03 20:05 UTC, gikf commented
Changing the system time first appears to make test pass. I'm not very convinced that was the main issue, it looks more to me like some fix as a side-effect.

2022-11-05 10:24 UTC, Sboonny commented
Is the issue in `eventWithoutUrl`? as it start in the past, but the new function doesn't send email about old events.

```json
 "eventWithoutURL": {
    "name": "Test Event",
    "description": "Test Description",
    "streaming_url": "https://test.event.org/video",
    "capacity": "10",
    "start_at": "2022-01-01T00:01",
    "ends_at": "2022-01-02T00:02",
    "venue_id": "1",
    "image_url": "https://test.event.org/image"
  },
 ```

2022-11-05 12:46 UTC, gikf commented
That default date should be overwritten in the `testEvent` here:
https://github.com/freeCodeCamp/chapter/blob/0280478fa16418fc89644c83cc994d8b13978af0/cypress/e2e/dashboard/chapters/%5BchapterId%5D/chapterId-index.cy.ts#L88-L92

2022-11-05 14:23 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2022-11-05 14:25 UTC, Sboonny commented
> That default date should be overwritten in the `testEvent` here:
> 
> https://github.com/freeCodeCamp/chapter/blob/0280478fa16418fc89644c83cc994d8b13978af0/cypress/e2e/dashboard/chapters/%5BchapterId%5D/chapterId-index.cy.ts#L88-L92

Yeah true, I can't think of why 😞. Should we add a comment about the issue in cypress file for context?

2022-11-08 12:01 UTC, ojeytonwilliams requested changes
@gikf nice work as always.

It's possible it could be organised a little differently, though.  Let me know what you think.

2022-11-08 19:30 UTC, gikf commented on client/src/modules/dashboard/Events/components/EventDatesForm.tsx
> +          {!startAt && isPast(startDate) && (
Yeah, it is. I'm gonna do that. I thought about some explicit prop for that, but couldn't really justify it to myself at the time.

2022-11-08 19:30 UTC, gikf commented on client/src/modules/dashboard/Events/components/EventDatesForm.tsx
> +  endsAt: Date | null;
You are right :+1:.

2022-11-09 09:15 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Events/components/EventDatesForm.tsx
> +  );
I'm probably a little too conservative when it comes to stuff like this.  This isn't a deeply weird pattern I've never seen before (we use it the fcc repo after all).

2022-11-09 16:22 UTC, ojeytonwilliams approved these changes

2022-11-09 16:23 UTC, merged