feat: add email mentioning and download button
freeCodeCamp/chapter pull request #1916
Opened 2022-11-17 14:50 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

follow up to #1890

Closes #XXXXX

2022-11-18 17:51 UTC, Sboonny commented
Creating the button will refactor the fields too much for small PR, this is enough to have the same functionality as previous code for now.

After this is merged, I will work on adding Download data button, that should be easier with different graphql fields

2022-11-18 17:56 UTC, Sboonny reviewed
Notes for the PR in the future

2022-11-18 17:56 UTC, Sboonny commented on client/src/modules/profiles/graphql/queries.ts
> +      }
for future, user_chapters have chapters in it, but the field doesn't allow for the client to request them, so the fields will be updated

2022-11-18 17:56 UTC, Sboonny commented on server/src/graphql-types/User.ts
> -}
wasn't used so deleted

2022-11-18 17:56 UTC, Sboonny commented on server/src/graphql-types/User.ts
> +export class UserInformation extends UserWithInstanceRole {
this is needed, so userinformation query have admined_chapters

But it won't be needed after refactoring so it should be reverted in the future PR

2022-11-21 14:07 UTC, ojeytonwilliams requested changes

2022-11-21 14:07 UTC, ojeytonwilliams commented on client/src/modules/profiles/pages/userProfile.tsx
> +            This will change the setting in{' '}
```suggestion
            Email address:{' '}
```
This seems clearer.  Ideally the styling should be uniform across Email address, Name and Profile picture, but that doesn't have to be this PR.

2022-11-21 14:13 UTC, Sboonny commented on server/src/controllers/User/resolver.ts
> +        id: ctx.user?.id,
I think to please typescript, meQuery which create userInformation can be null, so userInformation can be undefined.

Will test it out and give updated feedback

2022-11-21 14:23 UTC, Sboonny commented on server/src/controllers/User/resolver.ts
> +        id: ctx.user?.id,
Yeab to please TypeScript. The server run without issue, and  `npm run gen` is running without issues

2022-11-21 14:32 UTC, ojeytonwilliams commented on server/src/controllers/User/resolver.ts
> +        id: ctx.user?.id,
Right, but you can return early if `ctx.user` is `null` and avoid querying unnecessarily.

2022-11-21 14:32 UTC, Sboonny commented on server/src/controllers/User/resolver.ts
>          id: ctx.user.id,
```suggestion
        id: ctx.user?.id,

2022-11-21 14:40 UTC, Sboonny commented on server/src/controllers/User/resolver.ts
> +        id: ctx.user?.id,
But typescript will complain about the possibility of the object being null/undefined

and I would have to update the promise type `Promise<UserInformation | undefined>`, `Promise<UserInformation | null>`, which isn't true type of what userInformation should be.

I am adding `if (!ctx.user) return undefined` before 


```ts
    if (!ctx.user) return undefined
    return await prisma.users.findFirstOrThrow({
      where: {
        id: ctx.user?.id,
        ...
```

2022-11-21 16:50 UTC, ojeytonwilliams commented on server/src/controllers/User/resolver.ts
> +        id: ctx.user?.id,
That's true.  We can go one of two ways: throw an error if `ctx.user` is missing (and handle the error response on the client) or return `null` if `ctx.user` is missing (...and handle _that_ on the client).  Either seems fine for now.

We shouldn't call the db when we know for sure that it hasn't got the data.

2022-11-22 06:09 UTC, Sboonny commented on server/src/controllers/User/resolver.ts
> +      console.log('Unable to download Data');
```suggestion
      console.log('Unable to fetch attendee data');
```

2022-11-22 10:36 UTC, ojeytonwilliams approved these changes
I reverted the query to return early, so that we don't make a query when we already know it will return null.

This doesn't change anything on the client side since any request can fail and the client is able to handle that.

2022-11-22 10:47 UTC, merged