feat: polish Chapter Card layout
freeCodeCamp/chapter pull request #1922
Opened 2022-11-18 13:30 UTC by Sboonny

- [] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [] My pull request targets the `main` branch of Chapter.

A cleaner follow-up to #1711, without the noises related to other changes I have added

Closes #XXXXX

2022-11-20 13:23 UTC, Sboonny commented
IDK, which is better

![image](https://user-images.githubusercontent.com/88248797/202904383-764d148b-0ab2-4d59-a52f-78b9aa669b73.png)

![image](https://user-images.githubusercontent.com/88248797/202904498-be8ae279-c419-45c7-8bb2-25277ca45f30.png)

2022-11-20 13:26 UTC, Sboonny commented
Maybe it's better to swap about section and new events section :thinking:

2022-11-24 16:03 UTC, Sboonny commented
Moving the filter function into its own PR, like how event are filtered in home page

2022-11-29 14:51 UTC, ojeytonwilliams requested changes
It's looking much nicer, @Sboonny!

Just some nitpicks:

2022-11-29 14:51 UTC, ojeytonwilliams commented on client/src/components/ChapterCard.tsx
> +            <>
```suggestion
```
There's only one child

2022-11-29 14:51 UTC, ojeytonwilliams commented on client/src/components/ChapterCard.tsx
> +            <>
This will mess up the formatting, sorry!

2022-11-29 15:23 UTC, Sboonny commented on client/src/components/ChapterCard.tsx
> +              <Link key={id} href={`/events/${id}`} _hover={{}}>
Yeab, that reminds me, I should make a consistent style for links 😵‍💫

2022-11-30 09:09 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-11-30 09:10 UTC, merged