feat: turn the user image in nav into a menu
freeCodeCamp/chapter pull request #2023
Opened 2022-12-03 12:24 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

This is the last feedback from the tester, that is possible for me to do. I am going back to doing what I was previous doing, which I forgot what it was 🤣.

Btw did someone faced a situation in which graphql just said "nope"?

![image](https://user-images.githubusercontent.com/88248797/205440813-1acc5c7f-b6d6-4804-a4fb-37500daf752a.png)

2022-12-03 12:26 UTC, Sboonny commented on client/src/components/PageLayout/Header.tsx
> +        <Link href="/">
```suggestion
        <Link
          href="/"
          _focus={{
            outlineColor: 'blue.600',
            outlineOffset: '5px',
          }}
          _focusVisible={{
            boxShadow: 'none',
          }}
        >

2022-12-03 15:13 UTC, Sboonny commented
Btw, this https://github.com/freeCodeCamp/chapter/pull/2023/commits/7b1f7350d0c9f3d05f0ef5a66695245373e1d32c didn't work because although chakra allow you to add `aira-control` it doesn't respect it and overwrite it, which lead to the component doesn't have the aria-control that I wanted

2022-12-04 18:58 UTC, gikf reviewed
I don't have much opinion on moving menu. What stands out for me, is having two Login/Logout buttons so close to each other.

2022-12-06 16:27 UTC, ojeytonwilliams requested changes
> This is the last feedback from the tester, that is possible for me to do

Which feedback was this?  I remember Estefania (I think) mentioning something about this, but I can't find anything in my notes :/

Anyways, to this PR. How about having logout in the menu, but login separate (as you have it right now)?  I think that's a fairly standard pattern, partly to encourage people to login and to make it less likely they accidentally sign out.

Also the ArrowUpDownIcon seems a little strange because there's no up. It's really a dropdown, so I think the icon should indicate that.

2022-12-06 16:45 UTC, Sboonny commented
> Which feedback was this? I remember Estefania (I think) mentioning something about this, but I can't find anything in my notes :/

I forgot who requested it 🤣, thank you for the reminder. It's in my DMs about.

She sent me, these 

![image](https://user-images.githubusercontent.com/88248797/205971636-dffd315e-c660-4d1e-a310-bcc3ce1fb963.png)

![image](https://user-images.githubusercontent.com/88248797/205971772-22f3a01f-77fb-481b-8125-a699599f220f.png)

2022-12-08 10:46 UTC, ojeytonwilliams requested changes

2022-12-08 10:46 UTC, ojeytonwilliams commented on client/src/components/PageLayout/Header.tsx
> +import { ArrowDownIcon } from '@chakra-ui/icons';
```suggestion
import { ChevronDownIcon } from '@chakra-ui/icons';
```
The chevron is a standard way of representing a collapsible menu, let's stick to UI elements people are familiar with.

2022-12-08 10:46 UTC, ojeytonwilliams commented on client/src/components/PageLayout/Header.tsx
> +                      <ArrowDownIcon
```suggestion
                      <ChevronDownIcon
```
Ideally this should flip from down to up as you go from collapsed to expanded, but it's fine to be static for this PR.

2022-12-08 10:55 UTC, ojeytonwilliams approved these changes
Cheers, @Sboonny, thanks for the a11y and UX improvements.

2022-12-08 11:08 UTC, merged