WIP: send an email to banned attendees
freeCodeCamp/chapter pull request #2038
Opened 2022-12-05 08:00 UTC by Sboonny

- [] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [] My pull request targets the `main` branch of Chapter.

Closes #2037
Ref #1767

2022-12-05 08:05 UTC, Sboonny commented
Wait, I thought both issues are the same 🤣, don't know why tho. 😅

2022-12-07 18:46 UTC, gikf reviewed
Text describing new privileges apply only to specific instance role change. For opposite change it's not right. Similarly, if more instance roles are added.

2022-12-08 07:27 UTC, Sboonny commented on server/src/controllers/Users/resolver.ts
> +    const emailSubject = `Your role has changed to ${newRole} in chapter's instances`;
```suggestion
    const emailSubject = `Your role has changed to ${newRole} in the chapter's instances`;

2022-12-08 08:34 UTC, Sboonny commented on cypress/e2e/dashboard/users.cy.ts
> +          `Hello, ${memberRole.name}<br />
```suggestion
          `Hello, ${memberToOwnerToMember.name}<br />

2022-12-09 09:18 UTC, ojeytonwilliams requested changes

2022-12-09 17:18 UTC, Sboonny commented on cypress/e2e/dashboard/users.cy.ts
> +          .should('include', `Hello, ${userName}<br />`)
```suggestion
          .should('include', `Hello, ${userName}.<br />`)
```

2022-12-09 18:22 UTC, ojeytonwilliams approved these changes
LGTM 👍

2022-12-09 18:22 UTC, merged