fix: outline for blue buttons
freeCodeCamp/chapter pull request #2050
Opened 2022-12-06 13:28 UTC by Sboonny

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Ref #2044

2022-12-06 16:02 UTC, Sboonny commented
Every change, I have made the past two days will create conflict with this, so we can add conflict tag until everything is merged

2022-12-07 10:32 UTC, ojeytonwilliams commented
Changing the outline really should not mean we have to change 25 files.

Chakra lets you define [colour schemes and variants](https://chakra-ui.com/docs/components/button/theming) of every component. So, rather than finding every blue button and altering its outline, why not create a default variant that has the outline you want?  Then you can just use those components and only need to configure them if there's a special case.

2022-12-07 13:56 UTC, ojeytonwilliams commented
Sure, I take the point about the number of changes.  It's just that once these components are set up it's really easy to keep things consistent and future PRs really will just change a few lines of code.

2022-12-07 13:57 UTC, ojeytonwilliams requested changes
Just to cut down on the diff noise:

2022-12-07 13:57 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
> +                  .map(({ size, text, href, colorScheme }) => (
```suggestion
                  .map(({ colorScheme, size, text, href }) => (
```

2022-12-07 13:57 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Chapters/pages/ChaptersPage.tsx
> +                        .map(({ size, text, href, colorScheme }) => (
```suggestion
                        .map(({ colorScheme, size, href, text }) => (
```

2022-12-08 14:20 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-12-08 14:22 UTC, merged