feat: move attendee to waitlist
freeCodeCamp/chapter pull request #2456
Opened 2023-03-09 11:56 UTC by gikf

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Ref #2330

---
- Adds moving attendee (confirmed) to the waitlist.

2023-03-09 12:58 UTC, ojeytonwilliams requested changes
Looks great! I only spotted a couple of minor things:

2023-03-09 13:23 UTC, gikf commented on cypress/e2e/dashboard/events/[eventId].cy.ts
> +        //cy.moveToWaitlist(eventId, confirmedUser.id).then(expectToBeRejected);
Oh, right. Good I added this placeholder comment, to not forget about adding cypress command to test if mutation is rejected for user :eyes:

2023-03-09 13:31 UTC, ojeytonwilliams commented on cypress/e2e/dashboard/events/[eventId].cy.ts
> +        //cy.moveToWaitlist(eventId, confirmedUser.id).then(expectToBeRejected);
Hahah, awesome. Mission accomplished, then!

2023-03-10 11:39 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2023-03-10 11:39 UTC, merged