Docs: Add Windows notes, .env section, make formatting consistent, fix typos to CONTRIBUTING.md
freeCodeCamp/chapter pull request #466
Opened 2021-03-30 03:30 UTC by allella

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

* Adds notes and improved the docs for Windows / Git for Windows / Git Bash users to start addressing #465 @paizle
* Added a **.env Configuration File** section and link to it to avoid confusion with .env and .env.example like in #462 @NorthDecoder 
* Made commands, command line output, and italics text consistent in the various sections
* Fix typos noted in #447 
* Format "Note:" text consistently
* Made "Prerequisite" software bold and consistent.
* Added better OS-specific notes and links for downloading Git, Docker, and Node.js

2021-03-30 03:52 UTC, allella commented
@paizle and @NorthDecoder I wanted to add you add you as reviewers but GitHub won't let me. I think we figured it's because you haven't already commented on the PR and/or something to do with starring the project or the freeCodeCamp team settings.

In any case, I'd appreciate if you can look at the changes.  Viewing it at https://github.com/allella/chapter/blob/docs/windows-contributing/CONTRIBUTING.md is the only sane way to review the changes.

2021-03-31 12:19 UTC, paizle commented
> 
> 
> @paizle and @NorthDecoder I wanted to add you add you as reviewers but GitHub won't let me. I think we figured it's because you haven't already commented on the PR and/or something to do with starring the project or the freeCodeCamp team settings.
> 
> In any case, I'd appreciate if you can look at the changes. Viewing it at https://github.com/allella/chapter/blob/docs/windows-contributing/CONTRIBUTING.md is the only sane way to review the changes.

The docs look ok to me. As far as I can tell, Git Bash on Windows seems to work fine for me at this point.

2021-03-31 14:29 UTC, ojeytonwilliams requested changes
This looks good  All I found was a single typo.

2021-03-31 14:29 UTC, ojeytonwilliams commented on CONTRIBUTING.md
> +2. Sync the latest changes from the upstream **Chapter** _master_ branch to your local fork's _master_ branch. This is very important to keep things syncronzied and avoid "merge conflicts".
```suggestion
2. Sync the latest changes from the upstream **Chapter** _master_ branch to your local fork's _master_ branch. This is very important to keep things synchronized and avoid "merge conflicts".
```

2021-03-31 16:51 UTC, allella commented
@nhcarrigan could you take a look at **Contributing Code >> Step 2 - Prepare the Development Environment** of my PR for [CONTRIBITING.md](https://github.com/allella/chapter/blob/docs/windows-contributing/CONTRIBUTING.md) to see if the Windows related terminal / shell notes look good?

2021-03-31 16:54 UTC, nhcarrigan commented
That section looks good to me. 🙂

2021-03-31 17:05 UTC, merged

2021-03-31 17:07 UTC, allella commented
@all-contributors add @nhcarrigan @ojeytonwilliams for docs