feat: email magic link in development
freeCodeCamp/chapter pull request #634
Opened 2021-06-22 17:58 UTC by ojeytonwilliams

- feat: send the magic link via email
- feat: wrap the link in an anchor tag

With https://github.com/freeCodeCamp/chapter/issues/445 in mind, this makes the login process a little more natural.

2021-06-22 18:47 UTC, ojeytonwilliams commented
Just to clarify, this should make the dev experience a bit smoother and provide a fallback for the demo.  The plan is still to provide Google auth for the demo and a few more options for the MVP.

2021-06-23 20:52 UTC, Zeko369 requested changes
I wouldn't mix resolvers into resolvers, create a new service here

2021-06-23 20:52 UTC, Zeko369 commented on server/controllers/Auth/resolver.ts
> +      });
```suggestion
      await new MailerService(
        [data.email],
        'Login to Chapter',
        `<a href=http://localhost:3000/auth/token?token=${token}>Click here to log in to chapter</a>`,
      ).sendEmail();
```

2021-06-24 07:11 UTC, ojeytonwilliams commented
> I wouldn't mix resolvers into resolvers, create a new service here

Thanks, I wasn't entirely confident this was right. Is the point that resolvers should just be concerned handling GraphQL queries/mutations?

2021-06-24 17:43 UTC, Zeko369 commented
Yup, when you annotate a class with `@Resolver` use it only in the typeGraphql context, because other stuff might break (args, ctx, other decorators)

2021-06-24 17:43 UTC, Zeko369 approved these changes

2021-06-24 17:43 UTC, merged