feat: email users when they RSVP
freeCodeCamp/chapter pull request #636
Opened 2021-06-23 10:45 UTC by ojeytonwilliams

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

TODO

- [ ] Worry about santizing/encoding
- [ ] Add a subscribe link?

2021-06-23 22:17 UTC, Zeko369 requested changes
Let's merge this for now, I've figured out how to handle calendar events + updates (https://chat.freecodecamp.org/channel/chapter?msg=isJwqcfWHxLiDsL72) so I'll add at some point before the demo

2021-06-24 06:26 UTC, ojeytonwilliams commented on server/controllers/Events/resolver.ts
> +import { format } from 'date-fns';
Thanks, I'll change that.  How about adding https://github.com/benmosher/eslint-plugin-import to catch these?

2021-06-24 06:53 UTC, ojeytonwilliams commented on server/controllers/Events/resolver.ts
> +    const queryObject = {
Oh, neat.  Sure, that looks good.

2021-06-24 22:26 UTC, Zeko369 commented on server/controllers/Events/resolver.ts
> +import { format } from 'date-fns';
![Yes](https://media1.giphy.com/media/hXDrTueJWAscK3xWQ2/200.gif)

2021-06-25 08:19 UTC, ojeytonwilliams commented on server/controllers/Events/resolver.ts
> +import { format } from 'date-fns';
Heh, cool.  I'll do that post-demo, since it's not super urgent.

2021-06-25 14:16 UTC, allella commented
Just a note that this is part of #110.

2021-06-29 22:26 UTC, merged

2021-06-30 01:04 UTC, allella commented
@Zeko369 does this close #110?

2021-06-30 12:21 UTC, Zeko369 commented
@allella yup