Added frontend Input Field Validations on the EventForm.tsx
freeCodeCamp/chapter pull request #707
Opened 2021-09-17 05:38 UTC by Ravichandra-C

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #430 

1. Added type prop to input component in the Event form page
2.removed the DefaultValue prop from input component since it is already
  getting set via UseForm react hook
3. changed the type of URL and Video URL fields to url

2021-09-17 09:02 UTC, ojeytonwilliams requested changes
Thanks a ton for this @Ravichandra-C.  I found a couple of minor things, but it's looking great.

2021-09-17 09:52 UTC, Ravichandra-C commented on server/src/app.ts
> +  const schema = await buildSchema({ resolvers, validate: true });
@ojeytonwilliams Sure, I'll update and commit the changes.

2021-09-17 10:00 UTC, Ravichandra-C commented on cypress/integration/dashboard/events.js
> +    cy.get('input[name=ends_at]').clear().type(fix.endAt);
@ojeytonwilliams I've made the suggested changes . Could you please review and merge it?

2021-09-17 10:02 UTC, Ravichandra-C commented on server/src/app.ts
> +  const schema = await buildSchema({ resolvers, validate: true });
@ojeytonwilliams ,I've made the requested changes. Could you please review?

2021-09-17 10:07 UTC, ojeytonwilliams approved these changes
LGTM :+1: thanks @Ravichandra-C!

2021-09-17 10:09 UTC, ojeytonwilliams commented
@Zeko369 this looks solid to me, but do you want to take a look?

2021-09-27 14:55 UTC, ojeytonwilliams commented
Let's move things along.  Thanks again for putting this together @Ravichandra-C!

2021-09-27 14:56 UTC, merged