Ux consistency
freeCodeCamp/chapter pull request #815
Opened 2021-11-20 10:04 UTC by Ravichandra-C

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #800 

1. Updated Chapter and Venue forms to be consistent with other forms.
2. Added Place holders to the forms.
3. Removed the details fields from Chapter form, Chapter Schema , Input types and resolvers

2021-11-20 10:07 UTC, Ravichandra-C commented
@ojeytonwilliams @allella , Could you please take a look at the placeholders used in the forms. I tried to use freecodecamp as an example chapter and wrote place holders depending on that in the forms. Is that ok?

2021-11-22 10:31 UTC, ojeytonwilliams requested changes
@Ravichandra-C I think those are good placeholders, I just found a few typos/inconsistencies.

The look and feel is way better, though.

2021-11-22 10:31 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
> +    placeholder: 'San Fransisco',
```suggestion
    placeholder: 'San Francisco',
```

2021-11-22 10:31 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
> +      'freeCodeCamp is a non-profit organization that helps people learn to code for free',
```suggestion
      'freeCodeCamp is a nonprofit organization that helps people learn to code for free',
```
Consistency with 'category' below.

2021-11-22 10:31 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Chapters/components/ChapterForm.tsx
> +    placeholder: 'www.freecodecamp.com',
```suggestion
    placeholder: 'www.freecodecamp.org',
```
Nitpick, .com just redirects to .org

2021-11-22 10:31 UTC, ojeytonwilliams commented on client/src/modules/dashboard/Venues/components/VenueForm.tsx
> +    placeholder: 'San fransisco',
```suggestion
    placeholder: 'San Francisco',
```

2021-11-22 10:34 UTC, ojeytonwilliams commented
@Ravichandra-C sorry about the failing CI, I pushed changes before merging the updates to graphql-codegen :man_facepalming:  They should resolve themselves next commit, but if they don't I'll fix it.

2021-11-22 13:47 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-11-22 13:48 UTC, merged