fix: use logged in user as chapter creator
freeCodeCamp/chapter pull request #859
Opened 2022-01-16 19:09 UTC by gikf

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

---

- Creating new chapter adds logged in user as creator.
- `ctx.user` is checked, so there's no complains that `creator_id` might be not set.
- `creator_id` is required in `chapters` model and `ObjectType`. 
- Making `creator_id` required in the `CreateChapterInputs` currently would be erroring, as data passed from client doesn't have currently `creator_id`. I couldn't figure a way, to add `creator_id` from the `ctx`, before type of `data` is checked in the mutation resolver. Some middleware or other `type-graphql` feature?

2022-01-17 17:01 UTC, ojeytonwilliams requested changes
Could you elaborate on your last point?

>Making creator_id required in the CreateChapterInputs currently would be erroring, as data passed from client doesn't have currently creator_id. I couldn't figure a way, to add creator_id from the ctx, before type of data is checked in the mutation resolver. Some middleware or other type-graphql feature?

the PR works nicely, so I wasn't quite sure what the problem was.

2022-01-17 21:21 UTC, gikf commented
> Could you elaborate on your last point?
> 
> > Making creator_id required in the CreateChapterInputs currently would be erroring, as data passed from client doesn't have currently creator_id. I couldn't figure a way, to add creator_id from the ctx, before type of data is checked in the mutation resolver. Some middleware or other type-graphql feature?
> 
> the PR works nicely, so I wasn't quite sure what the problem was.

Just a bit of my rambling :slightly_smiling_face:. 

Initially I've added `creator_id` to the `CreateChapterInputs`, but that was resulting in error, as client doesn't pass `creator_id` in the `data`. I thought it would be nice, if `creator_id` could be injected to the `data` from `ctx`, before it's used in the `createChapter` mutation. So `creator_id` could be added to `CreateChapterInputs` without errors.

`type-graphql` seem to have some features that might be capable of something like this. As I couldn't figure out how to do that I backed to leaving `creator_id` out of the `CreateChapterInputs`, and adding it inside of the `createChapter`.

2022-01-17 21:26 UTC, gikf commented on server/src/controllers/Chapter/inputs.ts
> +export class CreateChapterInputs implements Partial<Chapter> {
That was the idea, I might have been too optimistic about `Partial` then. Thanks for correction :rocket:.

2022-01-17 22:12 UTC, ojeytonwilliams commented on server/src/controllers/Chapter/inputs.ts
> +export class CreateChapterInputs implements Partial<Chapter> {
No worries, I thought/hoped it would work, but sadly not.  Fortunately `Omit` isn't too verbose here.

2022-01-18 10:09 UTC, ojeytonwilliams commented
Ah, I'm with you.  I played around with this for a bit and the answer seems to be "no", though I could be missing something.  The issue with middleware is that we can read the `args`, but they're just copies. Modifying them does nothing outside the middleware function.

We *can* modify the `context`, but the `user` object is already attached to that, so there's little to be gained there.

Also, I'm not 100% convinced we should do this, even if we could.  Currently we have a separation (user provided data in `data` and data about the user in `ctx.user`). I could be wrong, but I think it'll be helpful to keep this.  For one thing, we know that `data` comes from outside the server, and so needs handling carefully.

2022-01-18 10:10 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

Thanks again @gikf!

2022-01-18 10:11 UTC, merged